unclassified:
  globallibraries:
    libraries:
    - defaultVersion: "master"
      name: "jenkins-shared-library"
      retriever:
        modernSCM:
          scm:
            git:
              credentialsId: "github-key"
              remote: "git@github.com:agarat/example-shared-library.git"
